name: pARCHd Ultimate
favicon: null
layout_spectrum: 0.5244361
typography_spectrum: 0.5494987
title: 'pARCHd Ultimate | St. Louis, MO'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#305C38'
    - '#FFFFFB'
    - '#539BF1'
    - '#863171'
    - '#99F0AC'
  brandStrength: 0.25
  lightness: 0.01879699
  saturation: 0.7960581
  rhythmicContrast: 0.687958
purpose: []
